name: Build Evelion 1.2 Solution (Final Fix)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Install Windows SDK
      run: |
        # 确保安装完整 Windows SDK
        choco install -y windows-sdk-10.1

    - name: Create required lib directory
      run: |
        # 创建项目期望的目录结构
        mkdir Lib
        mkdir Lib\x86
        # 从 Windows SDK 复制所需库文件
        copy "C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\d3d11.lib" Lib\x86\

    - name: Build Solution
      run: |
        msbuild "sakura.sln" /p:Configuration=Release /p:Platform="x86" /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0.19041.0 /p:OutputPath=..\build_output

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./*
