name: Build Evelion 1.2 Solution (Fixed Direct3D Link)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. 检出代码（含子模块）
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2. 设置 MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # 3. 验证 Windows SDK 是否存在
    - name: Check Windows SDK
      run: |
        echo "Windows SDK 路径:"
        ls "C:\Program Files (x86)\Windows Kits\10\Lib"

    # 4. 构建解决方案（修复换行符问题）
    - name: Build Solution
      shell: cmd  # 强制使用 CMD 而非 PowerShell
      run: |
        mkdir ..\build_output
        msbuild "sakura.sln" /p:Configuration=Release /p:Platform="x86" ^
          /p:PlatformToolset=v143 ^
          /p:WindowsTargetPlatformVersion=10.0.19041.0 ^
          /p:OutputPath=..\build_output

    # 5. 上传制品
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ..\build_output\*
