name: Build Evelion 1.2 Solution (with Submodules)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. 检出主仓库并初始化子模块
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # 关键：递归初始化子模块
        fetch-depth: 0        # 获取完整历史（某些子模块需要）

    # 2. 设置 MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # 3. 还原 NuGet 包（包括子模块的依赖）
    - name: Restore NuGet packages
      run: nuget restore "sakura.sln"

    # 4. 构建解决方案（x86 Release）
    - name: Build Solution
      run: |
        # 确保输出目录存在
        mkdir ..\build_output
        msbuild "sakura.sln" /p:Configuration=Release /p:Platform="x86" /p:OutputPath=..\build_output

    # 5. 验证输出文件（调试用）
    - name: List build output
      run: dir ..\build_output /s

    # 6. 上传制品
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ..\build_output\*  # 明确指定上传内容
